version: "2"
services:
  ss:
    image: dreammo/ssserver:alpine
    container_name: ss-server
    restart: always
    ports:
      - 22:8888
    volumes:
      - /opt/ss/ss.json:/etc/shadowsocks.json
